[package]
name = "expand-braille-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
expand-braille = { path = '../library' }
clap = { version = '3.1', features = ['derive'] }
